### ISSUE TITLE
Maven repository link is not working

### ISSUE THREAD

**Issue by naveenkg29** [java-decompiler/jd-core#1]
This link 

[https://raw.githubusercontent.com/java-decompiler/mvn-repo/master](url)

is not woking, please fix this

**Comment by emmanue1** [comment]
You can display this page, but the Maven repository is OK. "gradlew clean build" works fine.

**Comment by emmanue1** [comment]
JD-Core artifacts have been added to JFrog Bintray Maven repository : https://jcenter.bintray.com/org/jd/jd-core

**Comment by HuaienZhang** [comment]
> JD-Core artifacts have been added to JFrog Bintray Maven repository : https://jcenter.bintray.com/org/jd/jd-core

It has been closed.
