### ISSUE TITLE
Programmatically use of decompiler Error

### ISSUE THREAD

**Issue by PetraSt** [java-decompiler/jd-core#2]
Hello,
I tried to use the dj-core in my program and I faced the follow issue:
I used the example from README file and when I call 
decompiler.decompile(loader, printer, "C:\\Path\\to\\myclass.class"); 
I get a NullPointerException. 
I would like to know if this is happening because of me  or it is something else.
the output is 
I use java 8 in windows environment and the latest version of jd-core 
`java.lang.NullPointerException
at org.jd.core.v1.service.converter.classfiletojavasyntax.processor.ConvertClassFileProcessor.process(ConvertClassFileProcessor.java:48)
at org.jd.core.v1.service.converter.classfiletojavasyntax.ClassFileToJavaSyntaxProcessor.process(ClassFileToJavaSyntaxProcessor.java:39)
at org.jd.core.v1.ClassFileToJavaSourceDecompiler.decompile(ClassFileToJavaSourceDecompiler.java:54)
at org.jd.core.v1.ClassFileToJavaSourceDecompiler.decompile(ClassFileToJavaSourceDecompiler.java:38)`
Kind regards 
Petra

**Comment by emmanue1** [comment]
The file "C:\Path\to\myclass.class" is not found by the deserializer. I suppose you are using the Loader implementation that appears on the home page. This implementation is an In Memory impementation. If you want decompiler a CLASS file from your file system, you have to create a new loader. Something like that:

````java
public class DirectoryLoader implements Loader {
    protected File base;

    public DirectoryLoader(File base) {
        this.base = base;
    }

    @Override
    public byte[] load(String internalName) throws LoaderException {
        File file = newFile(internalName);

        if (file.exists()) {
            try (FileInputStream in= new FileInputStream(file); ByteArrayOutputStream out=new ByteArrayOutputStream()) {
                byte[] buffer = new byte[1024];
                int read = in.read(buffer);

                while (read > 0) {
                    out.write(buffer, 0, read);
                    read = in.read(buffer);
                }

                return out.toByteArray();
            } catch (Exception e) {
                throw new LoaderException(e);
            }
        } else {
            return null;
        }
    }

    @Override
    public boolean canLoad(String internalName) {
        return newFile(internalName).exists();
    }
    
    protected File newFile(String internalName) {
        return new File(base, File.separatorChar + internalName.replace('.', File.separatorChar) + ".class");
    }
}
````

Some examples are available here :
- https://github.com/java-decompiler/jd-core/tree/master/src/test/java/org/jd/core/v1/loader
- https://github.com/java-decompiler/jd-gui/blob/master/services/src/main/java/org/jd/gui/util/decompiler/ContainerLoader.java

**Comment by PetraSt** [comment]
Thank you for the solution it worked!!
