### ISSUE TITLE
Casts are omitted when casting floating point and integers

### ISSUE THREAD

**Issue by Marcono1234** [java-decompiler/jd-core#34]
# Version
1.1.3+, Commit 7f01508

# Compiler
javac 11.0.5

# Description
See https://github.com/leibnitz27/cfr/issues/86

**Comment by emmanue1** [comment]
Oh ! What kind of human being can write this kind of thing?

**Comment by Marcono1234** [comment]
One who wants to discover the limitations of a decompiler ;)
