### ISSUE TITLE
Implement jd-cli for running in the terminal

### ISSUE THREAD

**Issue by oxr463** [java-decompiler/jd-core#40]
It would be great to have a simple tool for use on the command line. Then I could use it directly from Vim.

**Comment by oxr463** [comment]
@eredisg, any ideas?

**Comment by eredisg** [comment]
@oxr463 Seems like there is a CLI wrapper for jd-core here: 
https://github.com/kwart/jd-cmd

**Comment by oxr463** [comment]
> @oxr463 Seems like there is a CLI wrapper for jd-core here:
> https://github.com/kwart/jd-cmd

That's perfect! Thanks!
