### ISSUE TITLE
How can I generate Java source files from class file?

### ISSUE THREAD

**Issue by chenzhegodspeed** [java-decompiler/jd-core#6]
I have read sample example on home page. I can get string source information from a class files and I want to know is there an existing API can generate corresponding java source file.

**Comment by quickiwiki** [comment]
When you get result code here 

ClassFileToJavaSourceDecompiler decompiler = new ClassFileToJavaSourceDecompiler();

decompiler.decompile(loader, printer, "path/to/YourClass");

String source = printer.toString();

You could save the source to a file.

**Comment by chenzhegodspeed** [comment]
Well. That's the only way I can do. I have another question, how can I decompile all classes of a project folder together. I hope there is a better way rather than collecting each class file manually

**Comment by chenzhegodspeed** [comment]
@quickiwiki I got the source String with your code snippet. I find that there is no package information in this string.

**Comment by emmanue1** [comment]
The simplest way is to use JD-GUI. If you want to do it programmatically, use `Files.walk(...)` for example and `call decompiler.decompile(...)` for each CLASS file.

**Comment by chenzhegodspeed** [comment]
Thanks for your reply.
