### ISSUE TITLE
New library versions not available on jcenter

### ISSUE THREAD

**Issue by gtiwari333** [java-decompiler/jd-core#8]
I noticed version 1.0.9 and 1.0.8 are not available on jcenter repository.

Could you publish those?

https://jcenter.bintray.com/org/jd/jd-core/

**Comment by xaviergxf** [comment]
And they have not being updated on jd-gui project as well

**Comment by emmanue1** [comment]
JD-Core 1.1.0 has just been published on JCenter today.

**Comment by xaviergxf** [comment]
@emmanue1  can you please release a new version of jd-gui with the newest version jd-core ?

**Comment by emmanue1** [comment]
@xaviergxf : Yes. Probably tomorrow or after tomorrow.

**Comment by xaviergxf** [comment]
@emmanue1 thanks :)
